spring:
  datasource:
    url: jdbc:mysql://localhost:3306/table2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
# Max file size.
  servlet:
    multipart:
      max-file-size: 10MB
# Max request size.
      max-request-size: 100MB
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: upendra.j2ee@gmail.com
    password: MyMom&Dad123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:true  
             
file:
  upload:
    folder: D:\\Course\\Uploads\\



server:
  port: 7090
